on: pull_request
name: post sls info on PRs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: On open & synchronize
      uses: dschep/filter-event-action@master
      with:
        args: "['opened', 'synchronize'].includes(event.action)"
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: npm test
      uses: actions/npm@master
      with:
        args: test
    - name: sls deploy
      uses: serverless/github-action@master
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      with:
        args: deploy
    - name: Comment on PR
      uses: ./comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
