on: push
name: Deploy
jobs:
  onNon-deletedBranches:
    name: On non-deleted branches
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: On non-deleted branches
      uses: dschep/filter-event-action@master
      with:
        args: '!event.deleted'
    - name: npm install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: npm test
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: test
    - name: serverless deploy
      uses: serverless/github-action@master
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      with:
        args: deploy
